[package]
name = "pyn"
description = "A wrapper for the JavaScript package managers: npm, pnpm, and Yarn"
license = "MIT"
version = "0.3.1"
authors = ["mitchellhamilton <mitchell@hamil.town>"]
homepage = "https://github.com/Thinkmill/pyn"
repository = "https://github.com/Thinkmill/pyn"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

thiserror = "1.0"
serde_json = "1.0.64"
serde = { version = "1.0.125", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
