[package]
name = "pyn"
description = "A wrapper for the JavaScript package managers: npm, pnpm, Yarn and Bolt"
license = "MIT"
version = "0.1.0"
authors = ["mitchellhamilton <mitchell@hamil.town>"]
homepage = "https://github.com/Thinkmill/pyn"
repository = "https://github.com/Thinkmill/pyn"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde_json = "1.0.45"
serde = {version="1.0.104", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
