name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary: pyn
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            binary: pyn
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: pyn.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release
      - run: strip target/release/${{ matrix.binary }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}-${{ matrix.binary }}
          path: target/release/${{ matrix.binary }}
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@v1
        with:
          name: x86_64-pc-windows-msvc-pyn.exe
          path: binaries/x86_64-pc-windows-msvc/pyn.exe
      - name: Download Windows Binary
        uses: actions/download-artifact@v1
        with:
          name: x86_64-unknown-linux-musl-pyn
          path: binaries/x86_64-unknown-linux-musl/pyn
      - name: Download Mac Binary
        uses: actions/download-artifact@v1
        with:
          name: x86_64-apple-darwin-pyn
          path: binaries/x86_64-apple-darwin/pyn

      - run: apt-get install tree && tree binaries
